export const FRIENDSHIP_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  BLOCKED: "BLOCKED",
} as const;

export const EXPENSE_STATUS = {
  DRAFT: "DRAFT",
  OPEN: "OPEN",
  PAID: "PAID",
  CANCELED: "CANCELED",
} as const;

export const DOCUMENT_OCR_STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export const PARTICIPANT_STATUS = {
  PENDING: "PENDING",
  PIX_GENERATED: "PIX_GENERATED",
  PAID: "PAID",
  REFUSED: "REFUSED",
  CANCELED: "CANCELED",
} as const;

export const PIX_PAYMENT_STATUS = {
  CREATED: "CREATED",
  EXPIRED: "EXPIRED",
  PAID: "PAID",
  FAILED: "FAILED",
  CANCELED: "CANCELED",
} as const;
