import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  actionRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  authContent: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 20,
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  chip: {
    borderColor: "#CBD5E1",
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  chipActive: {
    backgroundColor: "#0F766E",
    borderColor: "#0F766E",
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  chipText: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "700",
  },
  chipTextActive: {
    color: "#FFFFFF",
  },
  content: {
    padding: 16,
    paddingBottom: 36,
  },
  dangerButton: {
    alignItems: "center",
    backgroundColor: "#FEE2E2",
    borderRadius: 8,
    marginTop: 12,
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  dangerButtonText: {
    color: "#991B1B",
    fontSize: 15,
    fontWeight: "800",
  },
  emptyText: {
    backgroundColor: "#F8FAFC",
    borderColor: "#E2E8F0",
    borderRadius: 8,
    borderWidth: 1,
    color: "#64748B",
    fontSize: 14,
    padding: 14,
  },
  eyebrow: {
    color: "#0F766E",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  feedback: {
    borderRadius: 8,
    marginBottom: 14,
    padding: 12,
  },
  feedbackError: {
    backgroundColor: "#FEE2E2",
  },
  feedbackErrorText: {
    color: "#991B1B",
  },
  feedbackSuccess: {
    backgroundColor: "#DCFCE7",
  },
  feedbackSuccessText: {
    color: "#166534",
  },
  feedbackText: {
    fontSize: 14,
    fontWeight: "700",
  },
  fieldLabel: {
    color: "#334155",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 8,
  },
  flex: {
    flex: 1,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "#E2E8F0",
    borderRadius: 8,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 12,
  },
  iconButtonText: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "800",
  },
  infoBox: {
    backgroundColor: "#EFF6FF",
    borderColor: "#BFDBFE",
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 12,
    padding: 12,
  },
  infoText: {
    color: "#1E3A8A",
    fontSize: 13,
    marginTop: 6,
  },
  infoTitle: {
    color: "#1D4ED8",
    fontSize: 13,
    fontWeight: "900",
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderColor: "#CBD5E1",
    borderRadius: 8,
    borderWidth: 1,
    color: "#0F172A",
    fontSize: 16,
    marginBottom: 12,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  listItem: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
  },
  listItemFooter: {
    color: "#64748B",
    fontSize: 13,
    marginTop: 4,
  },
  listItemHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  listItemText: {
    flex: 1,
  },
  listItemTitle: {
    color: "#0F172A",
    fontSize: 16,
    fontWeight: "800",
  },
  listItemValue: {
    color: "#0F766E",
    fontSize: 15,
    fontWeight: "900",
  },
  logo: {
    color: "#0F172A",
    fontSize: 38,
    fontWeight: "900",
    letterSpacing: 0,
  },
  mutedText: {
    color: "#64748B",
    fontSize: 14,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#0F766E",
    borderRadius: 8,
    justifyContent: "center",
    marginTop: 4,
    minHeight: 50,
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
  },
  screen: {
    backgroundColor: "#F1F5F9",
    flex: 1,
  },
  secondaryButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#E0F2FE",
    borderRadius: 8,
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: "#075985",
    fontSize: 14,
    fontWeight: "800",
  },
  section: {
    gap: 2,
  },
  sectionDivider: {
    color: "#334155",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 10,
    marginTop: 20,
  },
  sectionTitle: {
    color: "#0F172A",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 0,
    marginBottom: 14,
  },
  segmentedControl: {
    backgroundColor: "#E2E8F0",
    borderRadius: 8,
    flexDirection: "row",
    gap: 4,
    marginBottom: 18,
    marginTop: 28,
    padding: 4,
  },
  segmentButton: {
    alignItems: "center",
    borderRadius: 7,
    flex: 1,
    minHeight: 42,
    justifyContent: "center",
  },
  segmentButtonActive: {
    backgroundColor: "#FFFFFF",
  },
  segmentText: {
    color: "#64748B",
    fontSize: 14,
    fontWeight: "800",
  },
  segmentTextActive: {
    color: "#0F172A",
  },
  subtitle: {
    color: "#475569",
    fontSize: 16,
    lineHeight: 22,
    marginTop: 8,
  },
  summaryAmber: {
    backgroundColor: "#FEF3C7",
  },
  summaryBox: {
    borderRadius: 8,
    flex: 1,
    minHeight: 72,
    padding: 12,
  },
  summaryGreen: {
    backgroundColor: "#CCFBF1",
  },
  summaryLabel: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  summaryRow: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  summaryValue: {
    color: "#0F172A",
    fontSize: 19,
    fontWeight: "900",
    marginTop: 8,
  },
  tabBar: {
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  tabButton: {
    alignItems: "center",
    backgroundColor: "#E2E8F0",
    borderRadius: 8,
    flex: 1,
    minHeight: 40,
    justifyContent: "center",
  },
  tabButtonActive: {
    backgroundColor: "#0F172A",
  },
  tabText: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "900",
  },
  tabTextActive: {
    color: "#FFFFFF",
  },
  title: {
    color: "#0F172A",
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: 0,
    marginTop: 2,
  },
});
